create table if not exists production_units (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  created_at timestamptz not null default now()
);
alter table sectors add column if not exists unit_id uuid references production_units(id);
create index if not exists sectors_unit_idx on sectors(unit_id);
create table if not exists delivery_routes (
  id uuid primary key default gen_random_uuid(),
  unit_id uuid not null references production_units(id),
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);
create index if not exists delivery_routes_unit_idx on delivery_routes(unit_id);
create table if not exists stores (
  id uuid primary key default gen_random_uuid(),
  route_id uuid not null references delivery_routes(id),
  name text not null,
  access_token text not null unique default encode(gen_random_bytes(16), 'hex'),
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists stores_route_idx on stores(route_id);
create table if not exists store_product_mins (
  store_id uuid not null references stores(id) on delete cascade,
  product_id uuid not null references products(id) on delete cascade,
  min_quantity numeric(12,3) not null default 0 check (min_quantity >= 0),
  updated_at timestamptz not null default now(),
  primary key (store_id, product_id)
);
create index if not exists store_product_mins_product_idx on store_product_mins(product_id);
create table if not exists store_stock_reports (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references stores(id),
  product_id uuid not null references products(id),
  quantity_reported numeric(12,3) not null check (quantity_reported >= 0),
  submission_id uuid not null,
  created_at timestamptz not null default now()
);
create index if not exists store_stock_reports_store_product_idx on store_stock_reports(store_id, product_id, created_at desc);
create index if not exists store_stock_reports_submission_idx on store_stock_reports(submission_id);

alter table production_orders add column if not exists route_id uuid references delivery_routes(id);
alter table production_orders add column if not exists source text not null default 'manual' check (source in ('manual', 'auto_route'));
alter table production_orders alter column requested_by drop not null;
create index if not exists production_orders_route_idx on production_orders(route_id, status);

create table if not exists production_order_contributions (
  order_id uuid not null references production_orders(id) on delete cascade,
  store_id uuid not null references stores(id),
  sector_id uuid not null references sectors(id),
  quantity numeric(12,3) not null check (quantity > 0),
  updated_at timestamptz not null default now(),
  primary key (order_id, store_id)
);
create index if not exists production_order_contributions_sector_idx on production_order_contributions(sector_id);
-- Replicates the spreadsheet's "Pedido a Separar" (deficit) + per-route SUMIF consolidation,
-- but as a live production_orders row instead of a spreadsheet formula.
create or replace function sync_store_report_order()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_route_id uuid;
  v_sector_id uuid;
  v_min numeric(12,3);
  v_deficit numeric(12,3);
  v_order_id uuid;
  v_order_quantity numeric(12,3);
  v_existing_contribution numeric(12,3);
  v_new_total numeric(12,3);
begin
  select route_id into v_route_id from stores where id = new.store_id;
  select min_quantity into v_min from store_product_mins
    where store_id = new.store_id and product_id = new.product_id;

  -- product not assigned to this store: nothing to reconcile
  if v_min is null then
    return new;
  end if;

  select sector_id into v_sector_id from products where id = new.product_id;
  v_deficit := greatest(0, v_min - new.quantity_reported);

  select id, quantity into v_order_id, v_order_quantity
    from production_orders
    where route_id = v_route_id and product_id = new.product_id
      and source = 'auto_route' and status in ('pending', 'in_progress')
    order by created_at desc
    limit 1
    for update;

  select quantity into v_existing_contribution
    from production_order_contributions
    where order_id = v_order_id and store_id = new.store_id;

  if v_deficit = 0 then
    -- store is back at/above minimum: withdraw its contribution, if any
    if v_order_id is not null and v_existing_contribution is not null then
      delete from production_order_contributions
        where order_id = v_order_id and store_id = new.store_id;
      v_new_total := v_order_quantity - v_existing_contribution;
      if v_new_total <= 0 then
        update production_orders set status = 'cancelled' where id = v_order_id;
      else
        update production_orders set quantity = v_new_total where id = v_order_id;
      end if;
    end if;
    return new;
  end if;

  if v_order_id is null then
    insert into production_orders (product_id, route_id, quantity, status, priority, source, requested_by)
      values (new.product_id, v_route_id, v_deficit, 'pending', 'medium', 'auto_route', null)
      returning id into v_order_id;
    insert into production_order_contributions (order_id, store_id, sector_id, quantity)
      values (v_order_id, new.store_id, v_sector_id, v_deficit);
  elsif v_existing_contribution is not null then
    -- replace (not accumulate) — each report is a fresh snapshot of that store's stock
    update production_order_contributions
      set quantity = v_deficit, updated_at = now()
      where order_id = v_order_id and store_id = new.store_id;
    update production_orders
      set quantity = v_order_quantity + (v_deficit - v_existing_contribution)
      where id = v_order_id;
  else
    insert into production_order_contributions (order_id, store_id, sector_id, quantity)
      values (v_order_id, new.store_id, v_sector_id, v_deficit);
    update production_orders
      set quantity = v_order_quantity + v_deficit
      where id = v_order_id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_store_report_sync on store_stock_reports;
create trigger trg_store_report_sync
  after insert on store_stock_reports
  for each row execute function sync_store_report_order();
alter table production_units enable row level security;
alter table delivery_routes enable row level security;
alter table stores enable row level security;
alter table store_product_mins enable row level security;
alter table store_stock_reports enable row level security;
alter table production_order_contributions enable row level security;

-- production_units / delivery_routes: same open-read pattern as sectors
drop policy if exists production_units_select on production_units;
create policy production_units_select on production_units for select
  using (auth.role() = 'authenticated');
drop policy if exists production_units_admin_write on production_units;
create policy production_units_admin_write on production_units for all
  using (is_admin()) with check (is_admin());

drop policy if exists delivery_routes_select on delivery_routes;
create policy delivery_routes_select on delivery_routes for select
  using (auth.role() = 'authenticated');
drop policy if exists delivery_routes_admin_write on delivery_routes;
create policy delivery_routes_admin_write on delivery_routes for all
  using (is_admin()) with check (is_admin());

-- stores / store_product_mins / store_stock_reports: admin-only.
-- The public report form never uses this RLS path (it goes through the
-- service-role admin client after validating the store's access token),
-- so no policy is needed here for anonymous/authenticated insert.
drop policy if exists stores_admin_only on stores;
create policy stores_admin_only on stores for all
  using (is_admin()) with check (is_admin());

drop policy if exists store_product_mins_admin_only on store_product_mins;
create policy store_product_mins_admin_only on store_product_mins for all
  using (is_admin()) with check (is_admin());

drop policy if exists store_stock_reports_admin_select on store_stock_reports;
create policy store_stock_reports_admin_select on store_stock_reports for select
  using (is_admin());

-- production_order_contributions: same visibility as the orders they belong to.
-- No insert/update/delete policy — only the sync_store_report_order() trigger
-- (security definer) writes here, mirroring how stock_movements is immutable.
drop policy if exists production_order_contributions_select on production_order_contributions;
create policy production_order_contributions_select on production_order_contributions for select
  using (is_admin() or has_sector_access(sector_id));
-- Seed data for Unidade Rui Barbosa, extracted from the operator's Excel spreadsheet.
-- Idempotent: safe to run more than once.

-- 1. Production units
insert into production_units (name, slug) values
  ('Fábrica Osório de Paiva', 'osorio-de-paiva'),
  ('Unidade Rui Barbosa', 'rui-barbosa')
on conflict (slug) do nothing;

-- 2. Backfill existing sectors (Cozinha, Salgados, Folheados, Pães, Embalagem) to Fábrica Osório de Paiva
update sectors set unit_id = (select id from production_units where slug = 'osorio-de-paiva')
where unit_id is null;

-- 3. New sectors for Rui Barbosa
insert into sectors (name, slug, unit_id)
select v.name, v.slug, (select id from production_units where slug = 'rui-barbosa')
from (values
  ('Pão', 'pao-rui-barbosa'),
  ('Confeitaria', 'confeitaria-rui-barbosa')
) as v(name, slug)
where not exists (select 1 from sectors where slug = v.slug);

-- 4. Delivery routes
insert into delivery_routes (unit_id, name, slug)
select (select id from production_units where slug = 'rui-barbosa'), v.name, v.slug
from (values
  ('Rota 001', 'rota-001'),
  ('Rota 02', 'rota-02')
) as v(name, slug)
where not exists (select 1 from delivery_routes where slug = v.slug);

-- 5. Stores (32 lojas confirmadas; 'Cometa Luciano' excluído por ser loja desativada/legado)
insert into stores (route_id, name)
select r.id, v.name
from (values
  ('Dom Luís', 'rota-001'),
  ('Fátima', 'rota-001'),
  ('Jovita', 'rota-001'),
  ('Francisco Sá', 'rota-001'),
  ('Passaré', 'rota-001'),
  ('Maraponga', 'rota-001'),
  ('Kennedy', 'rota-001'),
  ('João Pessoa', 'rota-001'),
  ('São Paulo', 'rota-001'),
  ('Mondubim', 'rota-001'),
  ('João XIII', 'rota-001'),
  ('Barão do Rio Branco', 'rota-001'),
  ('Guará Aldeota', 'rota-001'),
  ('Guará Jacarecanga', 'rota-001'),
  ('Guará Joquei', 'rota-001'),
  ('Theberge', 'rota-001'),
  ('Guará Iracema', 'rota-001'),
  ('Montese', 'rota-001'),
  ('Rui Barbosa', 'rota-02'),
  ('Terrazo', 'rota-02'),
  ('Beni', 'rota-02'),
  ('Tibúrcio', 'rota-02'),
  ('Eusébio', 'rota-02'),
  ('Edilson', 'rota-02'),
  ('Guará Eusébio', 'rota-02'),
  ('Washington Soares', 'rota-02'),
  ('Guará Washington', 'rota-02'),
  ('Guará Dunas', 'rota-02'),
  ('Guará Iguatemi', 'rota-02'),
  ('Guará Luciano', 'rota-02'),
  ('Lagoa Santos', 'rota-02'),
  ('Lago Jacarey', 'rota-02')
) as v(name, route_slug)
join delivery_routes r on r.slug = v.route_slug
where not exists (select 1 from stores s where s.name = v.name);

-- 6. Product catalog (Pão + Confeitaria only — Diversos/embalagens fica fora do escopo desta automação)
insert into products (sector_id, name, sku, unit)
select sec.id, v.name, v.sku, 'un'
from (values
  ('PÃO DOGUINHO', '9000126', 'pao-rui-barbosa'),
  ('PÃO HOT DOG', '9000128', 'pao-rui-barbosa'),
  ('PÃO DE HAMBÚRGUER', '9000127', 'pao-rui-barbosa'),
  ('PÃO DE LEITE', '9000123', 'pao-rui-barbosa'),
  ('PÃO DE BATATA', '9000190', 'pao-rui-barbosa'),
  ('PÃO DE COCO', '9000130', 'pao-rui-barbosa'),
  ('PÃO DE COCO FORMA', '9000122', 'pao-rui-barbosa'),
  ('PÃO MINI ÁRABE', '9000161', 'pao-rui-barbosa'),
  ('FORMA INTEGRAL', '9000255', 'pao-rui-barbosa'),
  ('FORMA BRANCA', null, 'pao-rui-barbosa'),
  ('PÃO BRIOCHE', '9000254', 'pao-rui-barbosa'),
  ('CROSTATA', null, 'pao-rui-barbosa'),
  ('BOLO FAZENDEIRO MEDIO', '9000096', 'confeitaria-rui-barbosa'),
  ('CREME DE LEITE MEDIO', '9000090', 'confeitaria-rui-barbosa'),
  ('BOLO FORMIGUEIRO MEDIO', '9000100', 'confeitaria-rui-barbosa'),
  ('BOLO MESCLADO MEDIO', '9000102', 'confeitaria-rui-barbosa'),
  ('TORTA DE BRIGADEIRO', '9000109', 'confeitaria-rui-barbosa'),
  ('BOLO DE BANANA MEDIO', '9000091', 'confeitaria-rui-barbosa'),
  ('BOLO BANANA TAB', '9000093', 'confeitaria-rui-barbosa'),
  ('BOLO DE BANANA COM NINHO', '9000193', 'confeitaria-rui-barbosa'),
  ('DOCINHO BRIGADEIRO', '9000002', 'confeitaria-rui-barbosa'),
  ('DOCINHO CASADINHO', '9000105', 'confeitaria-rui-barbosa'),
  ('COOKIE', '9000251', 'confeitaria-rui-barbosa'),
  ('TARTELETE DE LIMAO', '9000107', 'confeitaria-rui-barbosa'),
  ('TARTELETE DE BRIGADEIRO', '9000106', 'confeitaria-rui-barbosa'),
  ('TARTELETE DE BANOFFE', '9000186', 'confeitaria-rui-barbosa'),
  ('TARTELETE DE NINHO COM NUTELLA', '9000252', 'confeitaria-rui-barbosa'),
  ('TARTELETE PISTACHE', '9000253', 'confeitaria-rui-barbosa'),
  ('PUDIM', '9000019', 'confeitaria-rui-barbosa'),
  ('PUDIM GRANDE UNIDADE', null, 'confeitaria-rui-barbosa'),
  ('PALHA ITALIANA', '900021', 'confeitaria-rui-barbosa'),
  ('PALHA ITALIANA PISTACHE', null, 'confeitaria-rui-barbosa'),
  ('BROWNIE TRADICIONAL', '9000198', 'confeitaria-rui-barbosa'),
  ('BOLO DE CENOURA MEDIO', null, 'confeitaria-rui-barbosa'),
  ('BOLO DE CENOURA PEQUENO', null, 'confeitaria-rui-barbosa'),
  ('VOVO MEDIO', null, 'confeitaria-rui-barbosa'),
  ('VOVO PEQUENO', null, 'confeitaria-rui-barbosa'),
  ('DUETTO MEDIO', null, 'confeitaria-rui-barbosa'),
  ('DUETTO PEQUENO', null, 'confeitaria-rui-barbosa')
) as v(name, sku, sector_slug)
join sectors sec on sec.slug = v.sector_slug
where not exists (select 1 from products p where p.name = v.name and p.sector_id = sec.id);

-- 7. Estoque mínimo por loja+produto, extraído da coluna ESTOQUE MÍNIMO de cada aba de loja
-- Observação: Lagoa Santos: planilha tinha rótulo de seção duplicado/ambíguo — resolvido via catálogo (36 produtos reconhecidos, 30 ignorados por não constarem no catálogo Pão/Confeitaria).
insert into store_product_mins (store_id, product_id, min_quantity)
select s.id, p.id, v.min_quantity
from (values
  ('Dom Luís', 'PÃO DOGUINHO', 'pao-rui-barbosa', 25),
  ('Dom Luís', 'PÃO HOT DOG', 'pao-rui-barbosa', 25),
  ('Dom Luís', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 15),
  ('Dom Luís', 'PÃO DE LEITE', 'pao-rui-barbosa', 25),
  ('Dom Luís', 'PÃO DE BATATA', 'pao-rui-barbosa', 15),
  ('Dom Luís', 'PÃO DE COCO', 'pao-rui-barbosa', 50),
  ('Dom Luís', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 8),
  ('Dom Luís', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 30),
  ('Dom Luís', 'FORMA INTEGRAL', 'pao-rui-barbosa', 15),
  ('Dom Luís', 'FORMA BRANCA', 'pao-rui-barbosa', 13),
  ('Dom Luís', 'PÃO BRIOCHE', 'pao-rui-barbosa', 15),
  ('Dom Luís', 'CROSTATA', 'pao-rui-barbosa', 50),
  ('Dom Luís', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 10),
  ('Dom Luís', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 10),
  ('Dom Luís', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 8),
  ('Dom Luís', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 8),
  ('Dom Luís', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 3),
  ('Dom Luís', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 10),
  ('Dom Luís', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Dom Luís', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 10),
  ('Dom Luís', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 25),
  ('Dom Luís', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 25),
  ('Dom Luís', 'COOKIE', 'confeitaria-rui-barbosa', 50),
  ('Dom Luís', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 35),
  ('Dom Luís', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 20),
  ('Dom Luís', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 20),
  ('Dom Luís', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 20),
  ('Dom Luís', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 20),
  ('Dom Luís', 'PUDIM', 'confeitaria-rui-barbosa', 20),
  ('Dom Luís', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Dom Luís', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 30),
  ('Dom Luís', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 30),
  ('Dom Luís', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 30),
  ('Dom Luís', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Dom Luís', 'BOLO DE CENOURA PEQUENO', 'confeitaria-rui-barbosa', 6),
  ('Dom Luís', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Dom Luís', 'VOVO PEQUENO', 'confeitaria-rui-barbosa', 6),
  ('Dom Luís', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Dom Luís', 'DUETTO PEQUENO', 'confeitaria-rui-barbosa', 6),
  ('Fátima', 'PÃO DOGUINHO', 'pao-rui-barbosa', 15),
  ('Fátima', 'PÃO HOT DOG', 'pao-rui-barbosa', 6),
  ('Fátima', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 6),
  ('Fátima', 'PÃO DE LEITE', 'pao-rui-barbosa', 30),
  ('Fátima', 'PÃO DE BATATA', 'pao-rui-barbosa', 15),
  ('Fátima', 'PÃO DE COCO', 'pao-rui-barbosa', 20),
  ('Fátima', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 10),
  ('Fátima', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 12),
  ('Fátima', 'FORMA INTEGRAL', 'pao-rui-barbosa', 8),
  ('Fátima', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Fátima', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Fátima', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Fátima', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Fátima', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Fátima', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Fátima', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Fátima', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Fátima', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 0),
  ('Fátima', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 10),
  ('Fátima', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 15),
  ('Fátima', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Fátima', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 5),
  ('Fátima', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 5),
  ('Fátima', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Fátima', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 5),
  ('Fátima', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 5),
  ('Fátima', 'PUDIM', 'confeitaria-rui-barbosa', 5),
  ('Fátima', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Fátima', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Fátima', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Jovita', 'PÃO DOGUINHO', 'pao-rui-barbosa', 15),
  ('Jovita', 'PÃO HOT DOG', 'pao-rui-barbosa', 10),
  ('Jovita', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Jovita', 'PÃO DE LEITE', 'pao-rui-barbosa', 25),
  ('Jovita', 'PÃO DE BATATA', 'pao-rui-barbosa', 13),
  ('Jovita', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Jovita', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 5),
  ('Jovita', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 25),
  ('Jovita', 'FORMA INTEGRAL', 'pao-rui-barbosa', 10),
  ('Jovita', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Jovita', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Jovita', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Jovita', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Jovita', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Jovita', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Jovita', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Jovita', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 1),
  ('Jovita', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Jovita', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Jovita', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 5),
  ('Jovita', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Jovita', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 8),
  ('Jovita', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Jovita', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 6),
  ('Jovita', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 7),
  ('Jovita', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Jovita', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Jovita', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Jovita', 'PUDIM', 'confeitaria-rui-barbosa', 5),
  ('Jovita', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Jovita', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Jovita', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Jovita', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Jovita', 'DUETTO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Francisco Sá', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Francisco Sá', 'PÃO HOT DOG', 'pao-rui-barbosa', 8),
  ('Francisco Sá', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Francisco Sá', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Francisco Sá', 'PÃO DE BATATA', 'pao-rui-barbosa', 15),
  ('Francisco Sá', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Francisco Sá', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 8),
  ('Francisco Sá', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 20),
  ('Francisco Sá', 'FORMA INTEGRAL', 'pao-rui-barbosa', 10),
  ('Francisco Sá', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Francisco Sá', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Francisco Sá', 'CROSTATA', 'pao-rui-barbosa', 30),
  ('Francisco Sá', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Francisco Sá', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Francisco Sá', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Francisco Sá', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Francisco Sá', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Francisco Sá', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Francisco Sá', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Francisco Sá', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 2),
  ('Francisco Sá', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Francisco Sá', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 6),
  ('Francisco Sá', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Francisco Sá', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 8),
  ('Francisco Sá', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Francisco Sá', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Francisco Sá', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Francisco Sá', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Francisco Sá', 'PUDIM', 'confeitaria-rui-barbosa', 5),
  ('Francisco Sá', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Francisco Sá', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Francisco Sá', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Passaré', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Passaré', 'PÃO HOT DOG', 'pao-rui-barbosa', 7),
  ('Passaré', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 5),
  ('Passaré', 'PÃO DE LEITE', 'pao-rui-barbosa', 15),
  ('Passaré', 'PÃO DE BATATA', 'pao-rui-barbosa', 8),
  ('Passaré', 'PÃO DE COCO', 'pao-rui-barbosa', 20),
  ('Passaré', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 3),
  ('Passaré', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('Passaré', 'FORMA INTEGRAL', 'pao-rui-barbosa', 10),
  ('Passaré', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Passaré', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Passaré', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Passaré', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Passaré', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Passaré', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Passaré', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Passaré', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Passaré', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Passaré', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Passaré', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 6),
  ('Passaré', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Passaré', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 6),
  ('Passaré', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Passaré', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 3),
  ('Passaré', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Passaré', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Passaré', 'PUDIM', 'confeitaria-rui-barbosa', 5),
  ('Passaré', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Passaré', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Passaré', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Maraponga', 'PÃO DOGUINHO', 'pao-rui-barbosa', 15),
  ('Maraponga', 'PÃO HOT DOG', 'pao-rui-barbosa', 7),
  ('Maraponga', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Maraponga', 'PÃO DE LEITE', 'pao-rui-barbosa', 30),
  ('Maraponga', 'PÃO DE BATATA', 'pao-rui-barbosa', 20),
  ('Maraponga', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Maraponga', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 3),
  ('Maraponga', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 20),
  ('Maraponga', 'FORMA INTEGRAL', 'pao-rui-barbosa', 10),
  ('Maraponga', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Maraponga', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Maraponga', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Maraponga', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Maraponga', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Maraponga', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Maraponga', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Maraponga', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Maraponga', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Maraponga', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Maraponga', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Maraponga', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Maraponga', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 6),
  ('Maraponga', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Maraponga', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 8),
  ('Maraponga', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Maraponga', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Maraponga', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 8),
  ('Maraponga', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 8),
  ('Maraponga', 'PUDIM', 'confeitaria-rui-barbosa', 5),
  ('Maraponga', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Maraponga', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Maraponga', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Maraponga', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Kennedy', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Kennedy', 'PÃO HOT DOG', 'pao-rui-barbosa', 8),
  ('Kennedy', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 5),
  ('Kennedy', 'PÃO DE LEITE', 'pao-rui-barbosa', 25),
  ('Kennedy', 'PÃO DE BATATA', 'pao-rui-barbosa', 10),
  ('Kennedy', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Kennedy', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 6),
  ('Kennedy', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 25),
  ('Kennedy', 'FORMA INTEGRAL', 'pao-rui-barbosa', 10),
  ('Kennedy', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Kennedy', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Kennedy', 'CROSTATA', 'pao-rui-barbosa', 30),
  ('Kennedy', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Kennedy', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Kennedy', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Kennedy', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Kennedy', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Kennedy', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Kennedy', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Kennedy', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Kennedy', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Kennedy', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 8),
  ('Kennedy', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Kennedy', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 5),
  ('Kennedy', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 3),
  ('Kennedy', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Kennedy', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Kennedy', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Kennedy', 'PUDIM', 'confeitaria-rui-barbosa', 8),
  ('Kennedy', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Kennedy', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Kennedy', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('João Pessoa', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('João Pessoa', 'PÃO HOT DOG', 'pao-rui-barbosa', 6),
  ('João Pessoa', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('João Pessoa', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('João Pessoa', 'PÃO DE BATATA', 'pao-rui-barbosa', 10),
  ('João Pessoa', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('João Pessoa', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 5),
  ('João Pessoa', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 8),
  ('João Pessoa', 'FORMA INTEGRAL', 'pao-rui-barbosa', 5),
  ('João Pessoa', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('João Pessoa', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('João Pessoa', 'CROSTATA', 'pao-rui-barbosa', 30),
  ('João Pessoa', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('João Pessoa', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('João Pessoa', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('João Pessoa', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('João Pessoa', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('João Pessoa', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('João Pessoa', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('João Pessoa', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('João Pessoa', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('João Pessoa', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 6),
  ('João Pessoa', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('João Pessoa', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 5),
  ('João Pessoa', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 5),
  ('João Pessoa', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('João Pessoa', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 5),
  ('João Pessoa', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 5),
  ('João Pessoa', 'PUDIM', 'confeitaria-rui-barbosa', 5),
  ('João Pessoa', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('João Pessoa', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('João Pessoa', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('João Pessoa', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('João Pessoa', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 0),
  ('João Pessoa', 'BOLO DE CENOURA PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('João Pessoa', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('João Pessoa', 'VOVO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('João Pessoa', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('João Pessoa', 'DUETTO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('São Paulo', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('São Paulo', 'PÃO HOT DOG', 'pao-rui-barbosa', 5),
  ('São Paulo', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 3),
  ('São Paulo', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('São Paulo', 'PÃO DE BATATA', 'pao-rui-barbosa', 6),
  ('São Paulo', 'PÃO DE COCO', 'pao-rui-barbosa', 20),
  ('São Paulo', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 3),
  ('São Paulo', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 15),
  ('São Paulo', 'FORMA INTEGRAL', 'pao-rui-barbosa', 6),
  ('São Paulo', 'CROSTATA', 'pao-rui-barbosa', 10),
  ('São Paulo', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('São Paulo', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('São Paulo', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('São Paulo', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('São Paulo', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('São Paulo', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('São Paulo', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('São Paulo', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('São Paulo', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('São Paulo', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 8),
  ('São Paulo', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('São Paulo', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 6),
  ('São Paulo', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 3),
  ('São Paulo', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('São Paulo', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 3),
  ('São Paulo', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 3),
  ('São Paulo', 'PUDIM', 'confeitaria-rui-barbosa', 5),
  ('São Paulo', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('São Paulo', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('São Paulo', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('São Paulo', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('São Paulo', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 0),
  ('São Paulo', 'BOLO DE CENOURA PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('São Paulo', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('São Paulo', 'VOVO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('São Paulo', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('São Paulo', 'DUETTO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Mondubim', 'PÃO DOGUINHO', 'pao-rui-barbosa', 7),
  ('Mondubim', 'PÃO HOT DOG', 'pao-rui-barbosa', 7),
  ('Mondubim', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Mondubim', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Mondubim', 'PÃO DE BATATA', 'pao-rui-barbosa', 8),
  ('Mondubim', 'PÃO DE COCO', 'pao-rui-barbosa', 20),
  ('Mondubim', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 6),
  ('Mondubim', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('Mondubim', 'FORMA INTEGRAL', 'pao-rui-barbosa', 8),
  ('Mondubim', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Mondubim', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Mondubim', 'CROSTATA', 'pao-rui-barbosa', 10),
  ('Mondubim', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Mondubim', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Mondubim', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Mondubim', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Mondubim', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Mondubim', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Mondubim', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Mondubim', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 3),
  ('Mondubim', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 5),
  ('Mondubim', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 5),
  ('Mondubim', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Mondubim', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 6),
  ('Mondubim', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Mondubim', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Mondubim', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Mondubim', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Mondubim', 'PUDIM', 'confeitaria-rui-barbosa', 4),
  ('Mondubim', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Mondubim', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Mondubim', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Mondubim', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Mondubim', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Mondubim', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Mondubim', 'VOVO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Mondubim', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Mondubim', 'DUETTO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('João XIII', 'PÃO DOGUINHO', 'pao-rui-barbosa', 5),
  ('João XIII', 'PÃO HOT DOG', 'pao-rui-barbosa', 5),
  ('João XIII', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 3),
  ('João XIII', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('João XIII', 'PÃO DE BATATA', 'pao-rui-barbosa', 3),
  ('João XIII', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('João XIII', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 3),
  ('João XIII', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('João XIII', 'FORMA INTEGRAL', 'pao-rui-barbosa', 3),
  ('João XIII', 'CROSTATA', 'pao-rui-barbosa', 10),
  ('João XIII', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('João XIII', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('João XIII', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('João XIII', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('João XIII', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('João XIII', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('João XIII', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('João XIII', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('João XIII', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('João XIII', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 6),
  ('João XIII', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('João XIII', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 5),
  ('João XIII', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 5),
  ('João XIII', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('João XIII', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 5),
  ('João XIII', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 5),
  ('João XIII', 'PUDIM', 'confeitaria-rui-barbosa', 6),
  ('João XIII', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('João XIII', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('João XIII', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('João XIII', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 0),
  ('João XIII', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('João XIII', 'VOVO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('João XIII', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Barão do Rio Branco', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Barão do Rio Branco', 'PÃO HOT DOG', 'pao-rui-barbosa', 10),
  ('Barão do Rio Branco', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Barão do Rio Branco', 'PÃO DE LEITE', 'pao-rui-barbosa', 20),
  ('Barão do Rio Branco', 'PÃO DE BATATA', 'pao-rui-barbosa', 10),
  ('Barão do Rio Branco', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Barão do Rio Branco', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 5),
  ('Barão do Rio Branco', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 25),
  ('Barão do Rio Branco', 'FORMA INTEGRAL', 'pao-rui-barbosa', 8),
  ('Barão do Rio Branco', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Barão do Rio Branco', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Barão do Rio Branco', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Barão do Rio Branco', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Barão do Rio Branco', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Barão do Rio Branco', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Barão do Rio Branco', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Barão do Rio Branco', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Barão do Rio Branco', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Barão do Rio Branco', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Barão do Rio Branco', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 6),
  ('Barão do Rio Branco', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Barão do Rio Branco', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 6),
  ('Barão do Rio Branco', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Barão do Rio Branco', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 6),
  ('Barão do Rio Branco', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Barão do Rio Branco', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Barão do Rio Branco', 'PUDIM', 'confeitaria-rui-barbosa', 5),
  ('Barão do Rio Branco', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Barão do Rio Branco', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Barão do Rio Branco', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Barão do Rio Branco', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Guará Aldeota', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Guará Aldeota', 'PÃO HOT DOG', 'pao-rui-barbosa', 10),
  ('Guará Aldeota', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Guará Aldeota', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Guará Aldeota', 'PÃO DE BATATA', 'pao-rui-barbosa', 10),
  ('Guará Aldeota', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Guará Aldeota', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 7),
  ('Guará Aldeota', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 15),
  ('Guará Aldeota', 'FORMA INTEGRAL', 'pao-rui-barbosa', 15),
  ('Guará Aldeota', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Guará Aldeota', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 15),
  ('Guará Aldeota', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 15),
  ('Guará Aldeota', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 15),
  ('Guará Aldeota', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 15),
  ('Guará Aldeota', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 3),
  ('Guará Aldeota', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 10),
  ('Guará Aldeota', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Guará Aldeota', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 6),
  ('Guará Aldeota', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 12),
  ('Guará Aldeota', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 12),
  ('Guará Aldeota', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Guará Aldeota', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 10),
  ('Guará Aldeota', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 10),
  ('Guará Aldeota', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Guará Aldeota', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Guará Aldeota', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Guará Aldeota', 'PUDIM', 'confeitaria-rui-barbosa', 0),
  ('Guará Aldeota', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Guará Aldeota', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Guará Aldeota', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Guará Aldeota', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Guará Jacarecanga', 'PÃO DOGUINHO', 'pao-rui-barbosa', 6),
  ('Guará Jacarecanga', 'PÃO HOT DOG', 'pao-rui-barbosa', 6),
  ('Guará Jacarecanga', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Guará Jacarecanga', 'PÃO DE LEITE', 'pao-rui-barbosa', 6),
  ('Guará Jacarecanga', 'PÃO DE BATATA', 'pao-rui-barbosa', 6),
  ('Guará Jacarecanga', 'PÃO DE COCO', 'pao-rui-barbosa', 15),
  ('Guará Jacarecanga', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 0),
  ('Guará Jacarecanga', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('Guará Jacarecanga', 'FORMA INTEGRAL', 'pao-rui-barbosa', 6),
  ('Guará Jacarecanga', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Guará Jacarecanga', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Guará Jacarecanga', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Guará Jacarecanga', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Guará Jacarecanga', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Guará Jacarecanga', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 1),
  ('Guará Jacarecanga', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Guará Jacarecanga', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Guará Jacarecanga', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 2),
  ('Guará Jacarecanga', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 5),
  ('Guará Jacarecanga', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 5),
  ('Guará Jacarecanga', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Guará Jacarecanga', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 6),
  ('Guará Jacarecanga', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 5),
  ('Guará Jacarecanga', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Guará Jacarecanga', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 5),
  ('Guará Jacarecanga', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 5),
  ('Guará Jacarecanga', 'PUDIM', 'confeitaria-rui-barbosa', 6),
  ('Guará Jacarecanga', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Guará Jacarecanga', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 10),
  ('Guará Jacarecanga', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 10),
  ('Guará Jacarecanga', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 10),
  ('Guará Joquei', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Guará Joquei', 'PÃO HOT DOG', 'pao-rui-barbosa', 10),
  ('Guará Joquei', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Guará Joquei', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Guará Joquei', 'PÃO DE BATATA', 'pao-rui-barbosa', 10),
  ('Guará Joquei', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Guará Joquei', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 5),
  ('Guará Joquei', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 12),
  ('Guará Joquei', 'FORMA INTEGRAL', 'pao-rui-barbosa', 10),
  ('Guará Joquei', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Guará Joquei', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Joquei', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Joquei', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Guará Joquei', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Joquei', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 1),
  ('Guará Joquei', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Guará Joquei', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Guará Joquei', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Guará Joquei', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 5),
  ('Guará Joquei', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 5),
  ('Guará Joquei', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Guará Joquei', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 6),
  ('Guará Joquei', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 5),
  ('Guará Joquei', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Guará Joquei', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 5),
  ('Guará Joquei', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 5),
  ('Guará Joquei', 'PUDIM', 'confeitaria-rui-barbosa', 6),
  ('Guará Joquei', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Guará Joquei', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Guará Joquei', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Guará Joquei', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Theberge', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Theberge', 'PÃO HOT DOG', 'pao-rui-barbosa', 10),
  ('Theberge', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Theberge', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Theberge', 'PÃO DE BATATA', 'pao-rui-barbosa', 10),
  ('Theberge', 'PÃO DE COCO', 'pao-rui-barbosa', 15),
  ('Theberge', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 5),
  ('Theberge', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 12),
  ('Theberge', 'FORMA INTEGRAL', 'pao-rui-barbosa', 10),
  ('Theberge', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Theberge', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Theberge', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Theberge', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Theberge', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Theberge', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 1),
  ('Theberge', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Theberge', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Theberge', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Theberge', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 5),
  ('Theberge', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 5),
  ('Theberge', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Theberge', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 6),
  ('Theberge', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 5),
  ('Theberge', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Theberge', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 5),
  ('Theberge', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 5),
  ('Theberge', 'PUDIM', 'confeitaria-rui-barbosa', 6),
  ('Theberge', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Theberge', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Theberge', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Theberge', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Guará Iracema', 'PÃO DOGUINHO', 'pao-rui-barbosa', 6),
  ('Guará Iracema', 'PÃO HOT DOG', 'pao-rui-barbosa', 4),
  ('Guará Iracema', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Guará Iracema', 'PÃO DE LEITE', 'pao-rui-barbosa', 6),
  ('Guará Iracema', 'PÃO DE BATATA', 'pao-rui-barbosa', 6),
  ('Guará Iracema', 'PÃO DE COCO', 'pao-rui-barbosa', 10),
  ('Guará Iracema', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 0),
  ('Guará Iracema', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 6),
  ('Guará Iracema', 'FORMA INTEGRAL', 'pao-rui-barbosa', 4),
  ('Guará Iracema', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Guará Iracema', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Guará Iracema', 'CROSTATA', 'pao-rui-barbosa', 10),
  ('Guará Iracema', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Guará Iracema', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Guará Iracema', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Guará Iracema', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Guará Iracema', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'COOKIE', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'PUDIM', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 6),
  ('Guará Iracema', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Guará Iracema', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 6),
  ('Guará Iracema', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'BOLO DE CENOURA PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'VOVO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Guará Iracema', 'DUETTO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'PÃO DOGUINHO', 'pao-rui-barbosa', 6),
  ('Montese', 'PÃO HOT DOG', 'pao-rui-barbosa', 4),
  ('Montese', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Montese', 'PÃO DE LEITE', 'pao-rui-barbosa', 6),
  ('Montese', 'PÃO DE BATATA', 'pao-rui-barbosa', 6),
  ('Montese', 'PÃO DE COCO', 'pao-rui-barbosa', 10),
  ('Montese', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 0),
  ('Montese', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 6),
  ('Montese', 'FORMA INTEGRAL', 'pao-rui-barbosa', 4),
  ('Montese', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Montese', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Montese', 'CROSTATA', 'pao-rui-barbosa', 10),
  ('Montese', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Montese', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Montese', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Montese', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Montese', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Montese', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Montese', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 2),
  ('Montese', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'COOKIE', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'PUDIM', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 6),
  ('Montese', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Montese', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 6),
  ('Montese', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'BOLO DE CENOURA PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'VOVO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Montese', 'DUETTO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Rui Barbosa', 'PÃO DOGUINHO', 'pao-rui-barbosa', 20),
  ('Rui Barbosa', 'PÃO HOT DOG', 'pao-rui-barbosa', 15),
  ('Rui Barbosa', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 5),
  ('Rui Barbosa', 'PÃO DE LEITE', 'pao-rui-barbosa', 30),
  ('Rui Barbosa', 'PÃO DE BATATA', 'pao-rui-barbosa', 8),
  ('Rui Barbosa', 'PÃO DE COCO', 'pao-rui-barbosa', 25),
  ('Rui Barbosa', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 8),
  ('Rui Barbosa', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 25),
  ('Rui Barbosa', 'FORMA INTEGRAL', 'pao-rui-barbosa', 10),
  ('Rui Barbosa', 'FORMA BRANCA', 'pao-rui-barbosa', 10),
  ('Rui Barbosa', 'PÃO BRIOCHE', 'pao-rui-barbosa', 3),
  ('Rui Barbosa', 'CROSTATA', 'pao-rui-barbosa', 30),
  ('Rui Barbosa', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Rui Barbosa', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Rui Barbosa', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Rui Barbosa', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Rui Barbosa', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 3),
  ('Rui Barbosa', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Rui Barbosa', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Rui Barbosa', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 5),
  ('Rui Barbosa', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 15),
  ('Rui Barbosa', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 15),
  ('Rui Barbosa', 'COOKIE', 'confeitaria-rui-barbosa', 40),
  ('Rui Barbosa', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 12),
  ('Rui Barbosa', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Rui Barbosa', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 6),
  ('Rui Barbosa', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Rui Barbosa', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Rui Barbosa', 'PUDIM', 'confeitaria-rui-barbosa', 10),
  ('Rui Barbosa', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 20),
  ('Rui Barbosa', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 20),
  ('Rui Barbosa', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 20),
  ('Rui Barbosa', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Rui Barbosa', 'BOLO DE CENOURA PEQUENO', 'confeitaria-rui-barbosa', 2),
  ('Rui Barbosa', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Rui Barbosa', 'VOVO PEQUENO', 'confeitaria-rui-barbosa', 3),
  ('Rui Barbosa', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Rui Barbosa', 'DUETTO PEQUENO', 'confeitaria-rui-barbosa', 5),
  ('Terrazo', 'PÃO DOGUINHO', 'pao-rui-barbosa', 12),
  ('Terrazo', 'PÃO HOT DOG', 'pao-rui-barbosa', 10),
  ('Terrazo', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Terrazo', 'PÃO DE LEITE', 'pao-rui-barbosa', 20),
  ('Terrazo', 'PÃO DE BATATA', 'pao-rui-barbosa', 12),
  ('Terrazo', 'PÃO DE COCO', 'pao-rui-barbosa', 15),
  ('Terrazo', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 6),
  ('Terrazo', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 15),
  ('Terrazo', 'FORMA INTEGRAL', 'pao-rui-barbosa', 8),
  ('Terrazo', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Terrazo', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Terrazo', 'CROSTATA', 'pao-rui-barbosa', 30),
  ('Terrazo', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Terrazo', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Terrazo', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Terrazo', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Terrazo', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Terrazo', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Terrazo', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Terrazo', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Terrazo', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 10),
  ('Terrazo', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 10),
  ('Terrazo', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Terrazo', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 8),
  ('Terrazo', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Terrazo', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Terrazo', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 8),
  ('Terrazo', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 8),
  ('Terrazo', 'PUDIM', 'confeitaria-rui-barbosa', 8),
  ('Terrazo', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Terrazo', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 20),
  ('Terrazo', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 20),
  ('Terrazo', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 20),
  ('Terrazo', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Terrazo', 'BOLO DE CENOURA PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Terrazo', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Terrazo', 'VOVO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Terrazo', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 0),
  ('Terrazo', 'DUETTO PEQUENO', 'confeitaria-rui-barbosa', 0),
  ('Beni', 'PÃO DOGUINHO', 'pao-rui-barbosa', 20),
  ('Beni', 'PÃO HOT DOG', 'pao-rui-barbosa', 15),
  ('Beni', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Beni', 'PÃO DE LEITE', 'pao-rui-barbosa', 30),
  ('Beni', 'PÃO DE BATATA', 'pao-rui-barbosa', 20),
  ('Beni', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Beni', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 10),
  ('Beni', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 20),
  ('Beni', 'FORMA INTEGRAL', 'pao-rui-barbosa', 10),
  ('Beni', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Beni', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Beni', 'CROSTATA', 'pao-rui-barbosa', 50),
  ('Beni', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Beni', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Beni', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Beni', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Beni', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Beni', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Beni', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 3),
  ('Beni', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 10),
  ('Beni', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 10),
  ('Beni', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Beni', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 8),
  ('Beni', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Beni', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Beni', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 8),
  ('Beni', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 8),
  ('Beni', 'PUDIM', 'confeitaria-rui-barbosa', 8),
  ('Beni', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 25),
  ('Beni', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 25),
  ('Beni', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 25),
  ('Tibúrcio', 'PÃO DOGUINHO', 'pao-rui-barbosa', 30),
  ('Tibúrcio', 'PÃO HOT DOG', 'pao-rui-barbosa', 9),
  ('Tibúrcio', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Tibúrcio', 'PÃO DE LEITE', 'pao-rui-barbosa', 30),
  ('Tibúrcio', 'PÃO DE BATATA', 'pao-rui-barbosa', 20),
  ('Tibúrcio', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Tibúrcio', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 5),
  ('Tibúrcio', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 15),
  ('Tibúrcio', 'FORMA INTEGRAL', 'pao-rui-barbosa', 15),
  ('Tibúrcio', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Tibúrcio', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Tibúrcio', 'CROSTATA', 'pao-rui-barbosa', 40),
  ('Tibúrcio', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Tibúrcio', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Tibúrcio', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Tibúrcio', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 2),
  ('Tibúrcio', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Tibúrcio', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Tibúrcio', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Tibúrcio', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Tibúrcio', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Tibúrcio', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 8),
  ('Tibúrcio', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Tibúrcio', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 0),
  ('Tibúrcio', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 0),
  ('Tibúrcio', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Tibúrcio', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 0),
  ('Tibúrcio', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 0),
  ('Tibúrcio', 'PUDIM', 'confeitaria-rui-barbosa', 0),
  ('Tibúrcio', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Tibúrcio', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 20),
  ('Tibúrcio', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 20),
  ('Tibúrcio', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 20),
  ('Eusébio', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Eusébio', 'PÃO HOT DOG', 'pao-rui-barbosa', 10),
  ('Eusébio', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Eusébio', 'PÃO DE LEITE', 'pao-rui-barbosa', 20),
  ('Eusébio', 'PÃO DE BATATA', 'pao-rui-barbosa', 15),
  ('Eusébio', 'PÃO DE COCO', 'pao-rui-barbosa', 40),
  ('Eusébio', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 6),
  ('Eusébio', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 15),
  ('Eusébio', 'FORMA INTEGRAL', 'pao-rui-barbosa', 10),
  ('Eusébio', 'CROSTATA', 'pao-rui-barbosa', 50),
  ('Eusébio', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Eusébio', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Eusébio', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Eusébio', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Eusébio', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Eusébio', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 8),
  ('Eusébio', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Eusébio', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 8),
  ('Eusébio', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Eusébio', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 8),
  ('Eusébio', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Eusébio', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 8),
  ('Eusébio', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Eusébio', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Eusébio', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 5),
  ('Eusébio', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 5),
  ('Eusébio', 'PUDIM', 'confeitaria-rui-barbosa', 6),
  ('Eusébio', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Eusébio', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 20),
  ('Eusébio', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 20),
  ('Eusébio', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 20),
  ('Edilson', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Edilson', 'PÃO HOT DOG', 'pao-rui-barbosa', 6),
  ('Edilson', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Edilson', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Edilson', 'PÃO DE BATATA', 'pao-rui-barbosa', 8),
  ('Edilson', 'PÃO DE COCO', 'pao-rui-barbosa', 10),
  ('Edilson', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 5),
  ('Edilson', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 15),
  ('Edilson', 'FORMA INTEGRAL', 'pao-rui-barbosa', 6),
  ('Edilson', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Edilson', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Edilson', 'CROSTATA', 'pao-rui-barbosa', 30),
  ('Edilson', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Edilson', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Edilson', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Edilson', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Edilson', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Edilson', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Edilson', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Edilson', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 2),
  ('Edilson', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 3),
  ('Edilson', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 3),
  ('Edilson', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Edilson', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 3),
  ('Edilson', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 3),
  ('Edilson', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Edilson', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 3),
  ('Edilson', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 0),
  ('Edilson', 'PUDIM', 'confeitaria-rui-barbosa', 0),
  ('Edilson', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Edilson', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Edilson', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Guará Eusébio', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Guará Eusébio', 'PÃO HOT DOG', 'pao-rui-barbosa', 8),
  ('Guará Eusébio', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Guará Eusébio', 'PÃO DE LEITE', 'pao-rui-barbosa', 15),
  ('Guará Eusébio', 'PÃO DE BATATA', 'pao-rui-barbosa', 10),
  ('Guará Eusébio', 'PÃO DE COCO', 'pao-rui-barbosa', 15),
  ('Guará Eusébio', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 4),
  ('Guará Eusébio', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('Guará Eusébio', 'FORMA INTEGRAL', 'pao-rui-barbosa', 6),
  ('Guará Eusébio', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Guará Eusébio', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Guará Eusébio', 'CROSTATA', 'pao-rui-barbosa', 30),
  ('Guará Eusébio', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Guará Eusébio', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Eusébio', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Eusébio', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Eusébio', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Guará Eusébio', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Eusébio', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Guará Eusébio', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 3),
  ('Guará Eusébio', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 10),
  ('Guará Eusébio', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 10),
  ('Guará Eusébio', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Guará Eusébio', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 6),
  ('Guará Eusébio', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Guará Eusébio', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Guará Eusébio', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Guará Eusébio', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Guará Eusébio', 'PUDIM', 'confeitaria-rui-barbosa', 8),
  ('Guará Eusébio', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Guará Eusébio', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 20),
  ('Guará Eusébio', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 20),
  ('Guará Eusébio', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 20),
  ('Washington Soares', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Washington Soares', 'PÃO HOT DOG', 'pao-rui-barbosa', 8),
  ('Washington Soares', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Washington Soares', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Washington Soares', 'PÃO DE BATATA', 'pao-rui-barbosa', 6),
  ('Washington Soares', 'PÃO DE COCO', 'pao-rui-barbosa', 15),
  ('Washington Soares', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 4),
  ('Washington Soares', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('Washington Soares', 'FORMA INTEGRAL', 'pao-rui-barbosa', 6),
  ('Washington Soares', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Washington Soares', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Washington Soares', 'CROSTATA', 'pao-rui-barbosa', 30),
  ('Washington Soares', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Washington Soares', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Washington Soares', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Washington Soares', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Washington Soares', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Washington Soares', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Washington Soares', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Washington Soares', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Washington Soares', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 0),
  ('Washington Soares', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 0),
  ('Washington Soares', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Washington Soares', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 0),
  ('Washington Soares', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 0),
  ('Washington Soares', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Washington Soares', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 0),
  ('Washington Soares', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 0),
  ('Washington Soares', 'PUDIM', 'confeitaria-rui-barbosa', 0),
  ('Washington Soares', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Washington Soares', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Washington Soares', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Washington Soares', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Guará Washington', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Guará Washington', 'PÃO HOT DOG', 'pao-rui-barbosa', 6),
  ('Guará Washington', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Guará Washington', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Guará Washington', 'PÃO DE BATATA', 'pao-rui-barbosa', 10),
  ('Guará Washington', 'PÃO DE COCO', 'pao-rui-barbosa', 15),
  ('Guará Washington', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 4),
  ('Guará Washington', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('Guará Washington', 'FORMA INTEGRAL', 'pao-rui-barbosa', 12),
  ('Guará Washington', 'FORMA BRANCA', 'pao-rui-barbosa', 6),
  ('Guará Washington', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Guará Washington', 'CROSTATA', 'pao-rui-barbosa', 40),
  ('Guará Washington', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Washington', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Washington', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Washington', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Washington', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 3),
  ('Guará Washington', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Guará Washington', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Guará Washington', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Guará Washington', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 10),
  ('Guará Washington', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 10),
  ('Guará Washington', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Guará Washington', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 10),
  ('Guará Washington', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 10),
  ('Guará Washington', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Guará Washington', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 8),
  ('Guará Washington', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 8),
  ('Guará Washington', 'PUDIM', 'confeitaria-rui-barbosa', 10),
  ('Guará Washington', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 3),
  ('Guará Washington', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Guará Washington', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Guará Washington', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Guará Washington', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Washington', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Washington', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Dunas', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Guará Dunas', 'PÃO HOT DOG', 'pao-rui-barbosa', 6),
  ('Guará Dunas', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Guará Dunas', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Guará Dunas', 'PÃO DE BATATA', 'pao-rui-barbosa', 15),
  ('Guará Dunas', 'PÃO DE COCO', 'pao-rui-barbosa', 25),
  ('Guará Dunas', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 4),
  ('Guará Dunas', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('Guará Dunas', 'FORMA INTEGRAL', 'pao-rui-barbosa', 5),
  ('Guará Dunas', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Guará Dunas', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Guará Dunas', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Guará Dunas', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Guará Dunas', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Guará Dunas', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Guará Dunas', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Guará Dunas', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Guará Dunas', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Guará Dunas', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Guará Dunas', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 6),
  ('Guará Dunas', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 10),
  ('Guará Dunas', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 10),
  ('Guará Dunas', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Guará Dunas', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 8),
  ('Guará Dunas', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Guará Dunas', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Guará Dunas', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Guará Dunas', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Guará Dunas', 'PUDIM', 'confeitaria-rui-barbosa', 5),
  ('Guará Dunas', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Guará Dunas', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 8),
  ('Guará Dunas', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Guará Dunas', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Guará Iguatemi', 'PÃO DOGUINHO', 'pao-rui-barbosa', 8),
  ('Guará Iguatemi', 'PÃO HOT DOG', 'pao-rui-barbosa', 6),
  ('Guará Iguatemi', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Guará Iguatemi', 'PÃO DE LEITE', 'pao-rui-barbosa', 8),
  ('Guará Iguatemi', 'PÃO DE BATATA', 'pao-rui-barbosa', 8),
  ('Guará Iguatemi', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Guará Iguatemi', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 4),
  ('Guará Iguatemi', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 15),
  ('Guará Iguatemi', 'FORMA INTEGRAL', 'pao-rui-barbosa', 8),
  ('Guará Iguatemi', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Guará Iguatemi', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Guará Iguatemi', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Guará Iguatemi', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Iguatemi', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Iguatemi', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Iguatemi', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 3),
  ('Guará Iguatemi', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Guará Iguatemi', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Guará Iguatemi', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Guará Iguatemi', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Guará Iguatemi', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 10),
  ('Guará Iguatemi', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 10),
  ('Guará Iguatemi', 'COOKIE', 'confeitaria-rui-barbosa', 30),
  ('Guará Iguatemi', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 8),
  ('Guará Iguatemi', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Guará Iguatemi', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 8),
  ('Guará Iguatemi', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 8),
  ('Guará Iguatemi', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 8),
  ('Guará Iguatemi', 'PUDIM', 'confeitaria-rui-barbosa', 5),
  ('Guará Iguatemi', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Guará Iguatemi', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Guará Iguatemi', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Guará Iguatemi', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Guará Luciano', 'PÃO DOGUINHO', 'pao-rui-barbosa', 15),
  ('Guará Luciano', 'PÃO HOT DOG', 'pao-rui-barbosa', 15),
  ('Guará Luciano', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Guará Luciano', 'PÃO DE LEITE', 'pao-rui-barbosa', 15),
  ('Guará Luciano', 'PÃO DE BATATA', 'pao-rui-barbosa', 15),
  ('Guará Luciano', 'PÃO DE COCO', 'pao-rui-barbosa', 50),
  ('Guará Luciano', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 10),
  ('Guará Luciano', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('Guará Luciano', 'FORMA INTEGRAL', 'pao-rui-barbosa', 8),
  ('Guará Luciano', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Guará Luciano', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Guará Luciano', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Guará Luciano', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Guará Luciano', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Guará Luciano', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Guará Luciano', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Guará Luciano', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Guará Luciano', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Guará Luciano', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Guará Luciano', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 5),
  ('Guará Luciano', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Guará Luciano', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 6),
  ('Guará Luciano', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Guará Luciano', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 8),
  ('Guará Luciano', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Guará Luciano', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 8),
  ('Guará Luciano', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Guará Luciano', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Guará Luciano', 'PUDIM', 'confeitaria-rui-barbosa', 8),
  ('Guará Luciano', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 0),
  ('Guará Luciano', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Guará Luciano', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Guará Luciano', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Lago Jacarey', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Lago Jacarey', 'PÃO HOT DOG', 'pao-rui-barbosa', 6),
  ('Lago Jacarey', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Lago Jacarey', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Lago Jacarey', 'PÃO DE BATATA', 'pao-rui-barbosa', 6),
  ('Lago Jacarey', 'PÃO DE COCO', 'pao-rui-barbosa', 7),
  ('Lago Jacarey', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 5),
  ('Lago Jacarey', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('Lago Jacarey', 'FORMA INTEGRAL', 'pao-rui-barbosa', 6),
  ('Lago Jacarey', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Lago Jacarey', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Lago Jacarey', 'CROSTATA', 'pao-rui-barbosa', 30),
  ('Lago Jacarey', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Lago Jacarey', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Lago Jacarey', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Lago Jacarey', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 6),
  ('Lago Jacarey', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 0),
  ('Lago Jacarey', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Lago Jacarey', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Lago Jacarey', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Lago Jacarey', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 15),
  ('Lago Jacarey', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 15),
  ('Lago Jacarey', 'COOKIE', 'confeitaria-rui-barbosa', 15),
  ('Lago Jacarey', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 10),
  ('Lago Jacarey', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 10),
  ('Lago Jacarey', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 10),
  ('Lago Jacarey', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 10),
  ('Lago Jacarey', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 8),
  ('Lago Jacarey', 'PUDIM', 'confeitaria-rui-barbosa', 10),
  ('Lago Jacarey', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 1),
  ('Lago Jacarey', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Lago Jacarey', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Lago Jacarey', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Lago Jacarey', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 1),
  ('Lagoa Santos', 'PÃO DOGUINHO', 'pao-rui-barbosa', 10),
  ('Lagoa Santos', 'PÃO HOT DOG', 'pao-rui-barbosa', 10),
  ('Lagoa Santos', 'PÃO DE HAMBÚRGUER', 'pao-rui-barbosa', 0),
  ('Lagoa Santos', 'PÃO DE LEITE', 'pao-rui-barbosa', 10),
  ('Lagoa Santos', 'PÃO DE BATATA', 'pao-rui-barbosa', 8),
  ('Lagoa Santos', 'PÃO DE COCO', 'pao-rui-barbosa', 30),
  ('Lagoa Santos', 'PÃO DE COCO FORMA', 'pao-rui-barbosa', 5),
  ('Lagoa Santos', 'PÃO MINI ÁRABE', 'pao-rui-barbosa', 10),
  ('Lagoa Santos', 'FORMA INTEGRAL', 'pao-rui-barbosa', 8),
  ('Lagoa Santos', 'FORMA BRANCA', 'pao-rui-barbosa', 0),
  ('Lagoa Santos', 'PÃO BRIOCHE', 'pao-rui-barbosa', 0),
  ('Lagoa Santos', 'CROSTATA', 'pao-rui-barbosa', 20),
  ('Lagoa Santos', 'BOLO FAZENDEIRO MEDIO', 'confeitaria-rui-barbosa', 10),
  ('Lagoa Santos', 'CREME DE LEITE MEDIO', 'confeitaria-rui-barbosa', 10),
  ('Lagoa Santos', 'BOLO FORMIGUEIRO MEDIO', 'confeitaria-rui-barbosa', 10),
  ('Lagoa Santos', 'BOLO MESCLADO MEDIO', 'confeitaria-rui-barbosa', 5),
  ('Lagoa Santos', 'TORTA DE BRIGADEIRO', 'confeitaria-rui-barbosa', 2),
  ('Lagoa Santos', 'BOLO DE BANANA MEDIO', 'confeitaria-rui-barbosa', 4),
  ('Lagoa Santos', 'BOLO BANANA TAB', 'confeitaria-rui-barbosa', 0),
  ('Lagoa Santos', 'BOLO DE BANANA COM NINHO', 'confeitaria-rui-barbosa', 4),
  ('Lagoa Santos', 'DOCINHO BRIGADEIRO', 'confeitaria-rui-barbosa', 6),
  ('Lagoa Santos', 'DOCINHO CASADINHO', 'confeitaria-rui-barbosa', 6),
  ('Lagoa Santos', 'COOKIE', 'confeitaria-rui-barbosa', 20),
  ('Lagoa Santos', 'TARTELETE DE LIMAO', 'confeitaria-rui-barbosa', 12),
  ('Lagoa Santos', 'TARTELETE DE BRIGADEIRO', 'confeitaria-rui-barbosa', 8),
  ('Lagoa Santos', 'TARTELETE DE BANOFFE', 'confeitaria-rui-barbosa', 0),
  ('Lagoa Santos', 'TARTELETE DE NINHO COM NUTELLA', 'confeitaria-rui-barbosa', 6),
  ('Lagoa Santos', 'TARTELETE PISTACHE', 'confeitaria-rui-barbosa', 6),
  ('Lagoa Santos', 'PUDIM', 'confeitaria-rui-barbosa', 8),
  ('Lagoa Santos', 'PUDIM GRANDE UNIDADE', 'confeitaria-rui-barbosa', 1),
  ('Lagoa Santos', 'PALHA ITALIANA', 'confeitaria-rui-barbosa', 15),
  ('Lagoa Santos', 'PALHA ITALIANA PISTACHE', 'confeitaria-rui-barbosa', 15),
  ('Lagoa Santos', 'BROWNIE TRADICIONAL', 'confeitaria-rui-barbosa', 15),
  ('Lagoa Santos', 'BOLO DE CENOURA MEDIO', 'confeitaria-rui-barbosa', 1),
  ('Lagoa Santos', 'VOVO MEDIO', 'confeitaria-rui-barbosa', 1),
  ('Lagoa Santos', 'DUETTO MEDIO', 'confeitaria-rui-barbosa', 1)
) as v(store_name, product_name, sector_slug, min_quantity)
join stores s on s.name = v.store_name
join sectors sec on sec.slug = v.sector_slug
join products p on p.name = v.product_name and p.sector_id = sec.id
on conflict (store_id, product_id) do update set min_quantity = excluded.min_quantity, updated_at = now();
