-- Embalagens (bloco DIVERSOS das abas de loja da planilha original) como terceiro setor da
-- Unidade Rui Barbosa, mais Chocotone/Panetone Empório na Confeitaria. Só as 13 lojas que
-- têm o bloco na planilha recebem estoque mínimo para esses itens.

insert into sectors (name, slug, unit_id)
select 'Embalagens', 'embalagens-rui-barbosa', (select id from production_units where slug = 'rui-barbosa')
where not exists (select 1 from sectors where slug = 'embalagens-rui-barbosa');

insert into products (sector_id, name, unit)
select (select id from sectors where slug = 'embalagens-rui-barbosa'), v.name, v.unit
from (values
  ('COPO 300 ML QUE EMPORIO É ESSE', 'pct'),
  ('EMB SUPORTE PARA COPO DE CAFÉ', 'un'),
  ('EMB CAIXA CENTO DE SALGADO', 'un'),
  ('EMB COPO CRISTAL 400 ML PERSONALIZADO', 'pct'),
  ('COPO TERMICO GRANDE', 'pct'),
  ('COPO TERMICO PEQUENO', 'pct'),
  ('LAMINA PARA PAO', 'pct'),
  ('LUVA DE FORNEIRO', 'un'),
  ('PAPEL BANDEIJA', 'pct'),
  ('SACO 02 PÃES', 'cx'),
  ('SACO 04 PÃES', 'cx'),
  ('SACO 06 PÃES', 'cx'),
  ('SACO 10 PÃES', 'cx'),
  ('SACO BAGUETE', 'cx'),
  ('SACO BOBINA GRANDE 40 X 58', 'un'),
  ('SACO BOBINA MED 28 X 40', 'un'),
  ('SACO BOBINA PEQUENO 18 X 30', 'un'),
  ('SACO DE TALHER', 'cx'),
  ('SACO PP 25 X 35', 'bobina'),
  ('TAMPA COM FURO 400 ML', 'pct'),
  ('TAMPA PARA COPO TERMICO PEQUENO', 'un'),
  ('TAMPA PARA COPO TERMICO GRANDE', 'un'),
  ('TAMPA SEM FURO 400 ML', 'fd'),
  ('ETIQUETA DE VALIDADE', 'un'),
  ('SACOLA IFOOD', 'pct'),
  ('BOBINA PDV', 'un'),
  ('ETIQUETA BALANÇA', 'un'),
  ('SACOLA PERSONALIZADA', 'un')
) as v(name, unit)
where not exists (
  select 1 from products p where p.name = v.name and p.sector_id = (select id from sectors where slug = 'embalagens-rui-barbosa')
);

insert into products (sector_id, name, unit, responsible_id)
select (select id from sectors where slug = 'confeitaria-rui-barbosa'), v.name, 'un',
       (select responsible_id from products where name = 'BOLO FAZENDEIRO MEDIO' limit 1)
from (values
  ('CHOCOTONE EMPORIO'),
  ('PANETONE EMPORIO')
) as v(name)
where not exists (select 1 from products p where p.name = v.name);

insert into store_product_mins (store_id, product_id, min_quantity)
select s.id, p.id, v.min_quantity
from (values
  ('Dom Luís', 'COPO 300 ML QUE EMPORIO É ESSE', 20),
  ('Dom Luís', 'EMB SUPORTE PARA COPO DE CAFÉ', 1),
  ('Dom Luís', 'EMB CAIXA CENTO DE SALGADO', 1),
  ('Dom Luís', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 20),
  ('Dom Luís', 'COPO TERMICO GRANDE', 5),
  ('Dom Luís', 'COPO TERMICO PEQUENO', 5),
  ('Dom Luís', 'LAMINA PARA PAO', 0),
  ('Dom Luís', 'LUVA DE FORNEIRO', 1),
  ('Dom Luís', 'PAPEL BANDEIJA', 3),
  ('Dom Luís', 'SACO 02 PÃES', 2),
  ('Dom Luís', 'SACO 04 PÃES', 0),
  ('Dom Luís', 'SACO 06 PÃES', 3),
  ('Dom Luís', 'SACO 10 PÃES', 3),
  ('Dom Luís', 'SACO BAGUETE', 0),
  ('Dom Luís', 'SACO BOBINA GRANDE 40 X 58', 2),
  ('Dom Luís', 'SACO BOBINA MED 28 X 40', 2),
  ('Dom Luís', 'SACO BOBINA PEQUENO 18 X 30', 2),
  ('Dom Luís', 'SACO DE TALHER', 2),
  ('Dom Luís', 'SACO PP 25 X 35', 1),
  ('Dom Luís', 'TAMPA COM FURO 400 ML', 15),
  ('Dom Luís', 'TAMPA PARA COPO TERMICO PEQUENO', 8),
  ('Dom Luís', 'TAMPA PARA COPO TERMICO GRANDE', 8),
  ('Dom Luís', 'TAMPA SEM FURO 400 ML', 5),
  ('Dom Luís', 'ETIQUETA DE VALIDADE', 2),
  ('Dom Luís', 'SACOLA IFOOD', 1),
  ('Dom Luís', 'BOBINA PDV', 2),
  ('Dom Luís', 'ETIQUETA BALANÇA', 3),
  ('Dom Luís', 'SACOLA PERSONALIZADA', 6),
  ('Dom Luís', 'CHOCOTONE EMPORIO', 50),
  ('Dom Luís', 'PANETONE EMPORIO', 50),
  ('Passaré', 'COPO 300 ML QUE EMPORIO É ESSE', 5),
  ('Passaré', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('Passaré', 'EMB CAIXA CENTO DE SALGADO', 0),
  ('Passaré', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 2),
  ('Passaré', 'COPO TERMICO GRANDE', 3),
  ('Passaré', 'COPO TERMICO PEQUENO', 3),
  ('Passaré', 'LAMINA PARA PAO', 0),
  ('Passaré', 'LUVA DE FORNEIRO', 1),
  ('Passaré', 'PAPEL BANDEIJA', 2),
  ('Passaré', 'SACO 02 PÃES', 2),
  ('Passaré', 'SACO 04 PÃES', 0),
  ('Passaré', 'SACO 06 PÃES', 3),
  ('Passaré', 'SACO 10 PÃES', 3),
  ('Passaré', 'SACO BAGUETE', 1),
  ('Passaré', 'SACO BOBINA GRANDE 40 X 58', 2),
  ('Passaré', 'SACO BOBINA MED 28 X 40', 2),
  ('Passaré', 'SACO BOBINA PEQUENO 18 X 30', 2),
  ('Passaré', 'SACO DE TALHER', 2),
  ('Passaré', 'SACO PP 25 X 35', 2),
  ('Passaré', 'TAMPA COM FURO 400 ML', 3),
  ('Passaré', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('Passaré', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('Passaré', 'TAMPA SEM FURO 400 ML', 1),
  ('Passaré', 'ETIQUETA DE VALIDADE', 2),
  ('Passaré', 'SACOLA IFOOD', 0),
  ('Passaré', 'BOBINA PDV', 0),
  ('Passaré', 'ETIQUETA BALANÇA', 0),
  ('Passaré', 'SACOLA PERSONALIZADA', 0),
  ('Passaré', 'CHOCOTONE EMPORIO', 50),
  ('Passaré', 'PANETONE EMPORIO', 50),
  ('Maraponga', 'COPO 300 ML QUE EMPORIO É ESSE', 5),
  ('Maraponga', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('Maraponga', 'EMB CAIXA CENTO DE SALGADO', 0),
  ('Maraponga', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 2),
  ('Maraponga', 'COPO TERMICO GRANDE', 3),
  ('Maraponga', 'COPO TERMICO PEQUENO', 3),
  ('Maraponga', 'LAMINA PARA PAO', 0),
  ('Maraponga', 'LUVA DE FORNEIRO', 1),
  ('Maraponga', 'PAPEL BANDEIJA', 2),
  ('Maraponga', 'SACO 02 PÃES', 2),
  ('Maraponga', 'SACO 04 PÃES', 0),
  ('Maraponga', 'SACO 06 PÃES', 3),
  ('Maraponga', 'SACO 10 PÃES', 3),
  ('Maraponga', 'SACO BAGUETE', 1),
  ('Maraponga', 'SACO BOBINA GRANDE 40 X 58', 1),
  ('Maraponga', 'SACO BOBINA MED 28 X 40', 1),
  ('Maraponga', 'SACO BOBINA PEQUENO 18 X 30', 1),
  ('Maraponga', 'SACO DE TALHER', 1),
  ('Maraponga', 'SACO PP 25 X 35', 1),
  ('Maraponga', 'TAMPA COM FURO 400 ML', 3),
  ('Maraponga', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('Maraponga', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('Maraponga', 'TAMPA SEM FURO 400 ML', 1),
  ('Maraponga', 'ETIQUETA DE VALIDADE', 3),
  ('Maraponga', 'SACOLA IFOOD', 0),
  ('Maraponga', 'BOBINA PDV', 0),
  ('Maraponga', 'ETIQUETA BALANÇA', 0),
  ('Maraponga', 'SACOLA PERSONALIZADA', 0),
  ('Maraponga', 'CHOCOTONE EMPORIO', 50),
  ('Maraponga', 'PANETONE EMPORIO', 50),
  ('São Paulo', 'COPO 300 ML QUE EMPORIO É ESSE', 5),
  ('São Paulo', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('São Paulo', 'EMB CAIXA CENTO DE SALGADO', 0),
  ('São Paulo', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 2),
  ('São Paulo', 'COPO TERMICO GRANDE', 3),
  ('São Paulo', 'COPO TERMICO PEQUENO', 3),
  ('São Paulo', 'LAMINA PARA PAO', 0),
  ('São Paulo', 'LUVA DE FORNEIRO', 1),
  ('São Paulo', 'PAPEL BANDEIJA', 2),
  ('São Paulo', 'SACO 02 PÃES', 2),
  ('São Paulo', 'SACO 04 PÃES', 0),
  ('São Paulo', 'SACO 06 PÃES', 3),
  ('São Paulo', 'SACO 10 PÃES', 3),
  ('São Paulo', 'SACO BAGUETE', 1),
  ('São Paulo', 'SACO BOBINA GRANDE 40 X 58', 2),
  ('São Paulo', 'SACO BOBINA MED 28 X 40', 2),
  ('São Paulo', 'SACO BOBINA PEQUENO 18 X 30', 2),
  ('São Paulo', 'SACO DE TALHER', 2),
  ('São Paulo', 'SACO PP 25 X 35', 2),
  ('São Paulo', 'TAMPA COM FURO 400 ML', 3),
  ('São Paulo', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('São Paulo', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('São Paulo', 'TAMPA SEM FURO 400 ML', 1),
  ('São Paulo', 'ETIQUETA DE VALIDADE', 2),
  ('São Paulo', 'SACOLA IFOOD', 0),
  ('São Paulo', 'BOBINA PDV', 0),
  ('São Paulo', 'ETIQUETA BALANÇA', 0),
  ('São Paulo', 'SACOLA PERSONALIZADA', 0),
  ('São Paulo', 'CHOCOTONE EMPORIO', 50),
  ('São Paulo', 'PANETONE EMPORIO', 50),
  ('Mondubim', 'COPO 300 ML QUE EMPORIO É ESSE', 5),
  ('Mondubim', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('Mondubim', 'EMB CAIXA CENTO DE SALGADO', 0),
  ('Mondubim', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 2),
  ('Mondubim', 'COPO TERMICO GRANDE', 3),
  ('Mondubim', 'COPO TERMICO PEQUENO', 3),
  ('Mondubim', 'LAMINA PARA PAO', 0),
  ('Mondubim', 'LUVA DE FORNEIRO', 1),
  ('Mondubim', 'PAPEL BANDEIJA', 2),
  ('Mondubim', 'SACO 02 PÃES', 2),
  ('Mondubim', 'SACO 04 PÃES', 0),
  ('Mondubim', 'SACO 06 PÃES', 2),
  ('Mondubim', 'SACO 10 PÃES', 2),
  ('Mondubim', 'SACO BAGUETE', 1),
  ('Mondubim', 'SACO BOBINA GRANDE 40 X 58', 1),
  ('Mondubim', 'SACO BOBINA MED 28 X 40', 1),
  ('Mondubim', 'SACO BOBINA PEQUENO 18 X 30', 1),
  ('Mondubim', 'SACO DE TALHER', 1),
  ('Mondubim', 'SACO PP 25 X 35', 1),
  ('Mondubim', 'TAMPA COM FURO 400 ML', 3),
  ('Mondubim', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('Mondubim', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('Mondubim', 'TAMPA SEM FURO 400 ML', 1),
  ('Mondubim', 'ETIQUETA DE VALIDADE', 1),
  ('Mondubim', 'SACOLA IFOOD', 0),
  ('Mondubim', 'BOBINA PDV', 0),
  ('Mondubim', 'ETIQUETA BALANÇA', 0),
  ('Mondubim', 'SACOLA PERSONALIZADA', 0),
  ('Mondubim', 'CHOCOTONE EMPORIO', 50),
  ('Mondubim', 'PANETONE EMPORIO', 50),
  ('João XIII', 'COPO 300 ML QUE EMPORIO É ESSE', 5),
  ('João XIII', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('João XIII', 'EMB CAIXA CENTO DE SALGADO', 0),
  ('João XIII', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 2),
  ('João XIII', 'COPO TERMICO GRANDE', 3),
  ('João XIII', 'COPO TERMICO PEQUENO', 3),
  ('João XIII', 'LAMINA PARA PAO', 1),
  ('João XIII', 'LUVA DE FORNEIRO', 1),
  ('João XIII', 'PAPEL BANDEIJA', 1),
  ('João XIII', 'SACO 02 PÃES', 2),
  ('João XIII', 'SACO 04 PÃES', 0),
  ('João XIII', 'SACO 06 PÃES', 2),
  ('João XIII', 'SACO 10 PÃES', 2),
  ('João XIII', 'SACO BAGUETE', 1),
  ('João XIII', 'SACO BOBINA GRANDE 40 X 58', 2),
  ('João XIII', 'SACO BOBINA MED 28 X 40', 2),
  ('João XIII', 'SACO BOBINA PEQUENO 18 X 30', 2),
  ('João XIII', 'SACO DE TALHER', 2),
  ('João XIII', 'SACO PP 25 X 35', 2),
  ('João XIII', 'TAMPA COM FURO 400 ML', 3),
  ('João XIII', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('João XIII', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('João XIII', 'TAMPA SEM FURO 400 ML', 1),
  ('João XIII', 'ETIQUETA DE VALIDADE', 2),
  ('João XIII', 'SACOLA IFOOD', 0),
  ('João XIII', 'BOBINA PDV', 0),
  ('João XIII', 'ETIQUETA BALANÇA', 0),
  ('João XIII', 'SACOLA PERSONALIZADA', 0),
  ('João XIII', 'CHOCOTONE EMPORIO', 50),
  ('João XIII', 'PANETONE EMPORIO', 50),
  ('Barão do Rio Branco', 'COPO 300 ML QUE EMPORIO É ESSE', 3),
  ('Barão do Rio Branco', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('Barão do Rio Branco', 'EMB CAIXA CENTO DE SALGADO', 0),
  ('Barão do Rio Branco', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 2),
  ('Barão do Rio Branco', 'COPO TERMICO GRANDE', 3),
  ('Barão do Rio Branco', 'COPO TERMICO PEQUENO', 3),
  ('Barão do Rio Branco', 'LAMINA PARA PAO', 0),
  ('Barão do Rio Branco', 'LUVA DE FORNEIRO', 1),
  ('Barão do Rio Branco', 'PAPEL BANDEIJA', 1),
  ('Barão do Rio Branco', 'SACO 02 PÃES', 2),
  ('Barão do Rio Branco', 'SACO 04 PÃES', 0),
  ('Barão do Rio Branco', 'SACO 06 PÃES', 2),
  ('Barão do Rio Branco', 'SACO 10 PÃES', 3),
  ('Barão do Rio Branco', 'SACO BAGUETE', 1),
  ('Barão do Rio Branco', 'SACO BOBINA GRANDE 40 X 58', 2),
  ('Barão do Rio Branco', 'SACO BOBINA MED 28 X 40', 2),
  ('Barão do Rio Branco', 'SACO BOBINA PEQUENO 18 X 30', 2),
  ('Barão do Rio Branco', 'SACO DE TALHER', 2),
  ('Barão do Rio Branco', 'SACO PP 25 X 35', 2),
  ('Barão do Rio Branco', 'TAMPA COM FURO 400 ML', 3),
  ('Barão do Rio Branco', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('Barão do Rio Branco', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('Barão do Rio Branco', 'TAMPA SEM FURO 400 ML', 1),
  ('Barão do Rio Branco', 'ETIQUETA DE VALIDADE', 2),
  ('Barão do Rio Branco', 'SACOLA IFOOD', 0),
  ('Barão do Rio Branco', 'BOBINA PDV', 0),
  ('Barão do Rio Branco', 'ETIQUETA BALANÇA', 0),
  ('Barão do Rio Branco', 'SACOLA PERSONALIZADA', 0),
  ('Barão do Rio Branco', 'CHOCOTONE EMPORIO', 0),
  ('Barão do Rio Branco', 'PANETONE EMPORIO', 0),
  ('Guará Aldeota', 'COPO 300 ML QUE EMPORIO É ESSE', 0),
  ('Guará Aldeota', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('Guará Aldeota', 'EMB CAIXA CENTO DE SALGADO', 0),
  ('Guará Aldeota', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 3),
  ('Guará Aldeota', 'COPO TERMICO GRANDE', 2),
  ('Guará Aldeota', 'COPO TERMICO PEQUENO', 2),
  ('Guará Aldeota', 'LAMINA PARA PAO', 0),
  ('Guará Aldeota', 'LUVA DE FORNEIRO', 1),
  ('Guará Aldeota', 'PAPEL BANDEIJA', 1),
  ('Guará Aldeota', 'SACO 02 PÃES', 2),
  ('Guará Aldeota', 'SACO 04 PÃES', 0),
  ('Guará Aldeota', 'SACO 06 PÃES', 2),
  ('Guará Aldeota', 'SACO 10 PÃES', 3),
  ('Guará Aldeota', 'SACO BAGUETE', 0),
  ('Guará Aldeota', 'SACO BOBINA GRANDE 40 X 58', 1),
  ('Guará Aldeota', 'SACO BOBINA MED 28 X 40', 1),
  ('Guará Aldeota', 'SACO BOBINA PEQUENO 18 X 30', 1),
  ('Guará Aldeota', 'SACO DE TALHER', 1),
  ('Guará Aldeota', 'SACO PP 25 X 35', 1),
  ('Guará Aldeota', 'TAMPA COM FURO 400 ML', 3),
  ('Guará Aldeota', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('Guará Aldeota', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('Guará Aldeota', 'TAMPA SEM FURO 400 ML', 1),
  ('Guará Aldeota', 'ETIQUETA DE VALIDADE', 2),
  ('Guará Aldeota', 'SACOLA IFOOD', 0),
  ('Guará Aldeota', 'BOBINA PDV', 0),
  ('Guará Aldeota', 'ETIQUETA BALANÇA', 0),
  ('Guará Aldeota', 'SACOLA PERSONALIZADA', 0),
  ('Rui Barbosa', 'COPO 300 ML QUE EMPORIO É ESSE', 5),
  ('Rui Barbosa', 'EMB SUPORTE PARA COPO DE CAFÉ', 5),
  ('Rui Barbosa', 'EMB CAIXA CENTO DE SALGADO', 5),
  ('Rui Barbosa', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 5),
  ('Rui Barbosa', 'COPO TERMICO GRANDE', 3),
  ('Rui Barbosa', 'COPO TERMICO PEQUENO', 3),
  ('Rui Barbosa', 'LAMINA PARA PAO', 5),
  ('Rui Barbosa', 'LUVA DE FORNEIRO', 2),
  ('Rui Barbosa', 'PAPEL BANDEIJA', 2),
  ('Rui Barbosa', 'SACO 02 PÃES', 2),
  ('Rui Barbosa', 'SACO 04 PÃES', 2),
  ('Rui Barbosa', 'SACO 06 PÃES', 2),
  ('Rui Barbosa', 'SACO 10 PÃES', 2),
  ('Rui Barbosa', 'SACO BAGUETE', 1),
  ('Rui Barbosa', 'SACO BOBINA GRANDE 40 X 58', 2),
  ('Rui Barbosa', 'SACO BOBINA MED 28 X 40', 2),
  ('Rui Barbosa', 'SACO BOBINA PEQUENO 18 X 30', 2),
  ('Rui Barbosa', 'SACO DE TALHER', 2),
  ('Rui Barbosa', 'SACO PP 25 X 35', 2),
  ('Rui Barbosa', 'TAMPA COM FURO 400 ML', 3),
  ('Rui Barbosa', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('Rui Barbosa', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('Rui Barbosa', 'TAMPA SEM FURO 400 ML', 1),
  ('Rui Barbosa', 'ETIQUETA DE VALIDADE', 3),
  ('Rui Barbosa', 'SACOLA IFOOD', 15),
  ('Rui Barbosa', 'BOBINA PDV', 15),
  ('Rui Barbosa', 'ETIQUETA BALANÇA', 15),
  ('Rui Barbosa', 'SACOLA PERSONALIZADA', 15),
  ('Rui Barbosa', 'CHOCOTONE EMPORIO', 50),
  ('Rui Barbosa', 'PANETONE EMPORIO', 50),
  ('Beni', 'COPO 300 ML QUE EMPORIO É ESSE', 5),
  ('Beni', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('Beni', 'EMB CAIXA CENTO DE SALGADO', 0),
  ('Beni', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 5),
  ('Beni', 'COPO TERMICO GRANDE', 3),
  ('Beni', 'COPO TERMICO PEQUENO', 3),
  ('Beni', 'LAMINA PARA PAO', 1),
  ('Beni', 'LUVA DE FORNEIRO', 1),
  ('Beni', 'PAPEL BANDEIJA', 2),
  ('Beni', 'SACO 02 PÃES', 2),
  ('Beni', 'SACO 04 PÃES', 0),
  ('Beni', 'SACO 06 PÃES', 3),
  ('Beni', 'SACO 10 PÃES', 3),
  ('Beni', 'SACO BAGUETE', 1),
  ('Beni', 'SACO BOBINA GRANDE 40 X 58', 1),
  ('Beni', 'SACO BOBINA MED 28 X 40', 1),
  ('Beni', 'SACO BOBINA PEQUENO 18 X 30', 1),
  ('Beni', 'SACO DE TALHER', 1),
  ('Beni', 'SACO PP 25 X 35', 1),
  ('Beni', 'TAMPA COM FURO 400 ML', 3),
  ('Beni', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('Beni', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('Beni', 'TAMPA SEM FURO 400 ML', 1),
  ('Beni', 'ETIQUETA DE VALIDADE', 2),
  ('Beni', 'SACOLA IFOOD', 0),
  ('Beni', 'BOBINA PDV', 0),
  ('Beni', 'ETIQUETA BALANÇA', 0),
  ('Beni', 'SACOLA PERSONALIZADA', 0),
  ('Beni', 'CHOCOTONE EMPORIO', 100),
  ('Beni', 'PANETONE EMPORIO', 100),
  ('Tibúrcio', 'COPO 300 ML QUE EMPORIO É ESSE', 5),
  ('Tibúrcio', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('Tibúrcio', 'EMB CAIXA CENTO DE SALGADO', 0),
  ('Tibúrcio', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 5),
  ('Tibúrcio', 'COPO TERMICO GRANDE', 3),
  ('Tibúrcio', 'COPO TERMICO PEQUENO', 3),
  ('Tibúrcio', 'LAMINA PARA PAO', 0),
  ('Tibúrcio', 'LUVA DE FORNEIRO', 1),
  ('Tibúrcio', 'PAPEL BANDEIJA', 2),
  ('Tibúrcio', 'SACO 02 PÃES', 2),
  ('Tibúrcio', 'SACO 04 PÃES', 0),
  ('Tibúrcio', 'SACO 06 PÃES', 3),
  ('Tibúrcio', 'SACO 10 PÃES', 3),
  ('Tibúrcio', 'SACO BAGUETE', 1),
  ('Tibúrcio', 'SACO BOBINA GRANDE 40 X 58', 1),
  ('Tibúrcio', 'SACO BOBINA MED 28 X 40', 1),
  ('Tibúrcio', 'SACO BOBINA PEQUENO 18 X 30', 1),
  ('Tibúrcio', 'SACO DE TALHER', 1),
  ('Tibúrcio', 'SACO PP 25 X 35', 1),
  ('Tibúrcio', 'TAMPA COM FURO 400 ML', 3),
  ('Tibúrcio', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('Tibúrcio', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('Tibúrcio', 'TAMPA SEM FURO 400 ML', 1),
  ('Tibúrcio', 'ETIQUETA DE VALIDADE', 2),
  ('Tibúrcio', 'SACOLA IFOOD', 0),
  ('Tibúrcio', 'BOBINA PDV', 0),
  ('Tibúrcio', 'ETIQUETA BALANÇA', 0),
  ('Tibúrcio', 'SACOLA PERSONALIZADA', 0),
  ('Tibúrcio', 'CHOCOTONE EMPORIO', 50),
  ('Tibúrcio', 'PANETONE EMPORIO', 50),
  ('Eusébio', 'COPO 300 ML QUE EMPORIO É ESSE', 5),
  ('Eusébio', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('Eusébio', 'EMB CAIXA CENTO DE SALGADO', 1),
  ('Eusébio', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 5),
  ('Eusébio', 'COPO TERMICO GRANDE', 3),
  ('Eusébio', 'COPO TERMICO PEQUENO', 3),
  ('Eusébio', 'LAMINA PARA PAO', 1),
  ('Eusébio', 'LUVA DE FORNEIRO', 1),
  ('Eusébio', 'PAPEL BANDEIJA', 2),
  ('Eusébio', 'SACO 02 PÃES', 2),
  ('Eusébio', 'SACO 04 PÃES', 0),
  ('Eusébio', 'SACO 06 PÃES', 3),
  ('Eusébio', 'SACO 10 PÃES', 3),
  ('Eusébio', 'SACO BAGUETE', 1),
  ('Eusébio', 'SACO BOBINA GRANDE 40 X 58', 2),
  ('Eusébio', 'SACO BOBINA MED 28 X 40', 2),
  ('Eusébio', 'SACO BOBINA PEQUENO 18 X 30', 2),
  ('Eusébio', 'SACO DE TALHER', 2),
  ('Eusébio', 'SACO PP 25 X 35', 2),
  ('Eusébio', 'TAMPA COM FURO 400 ML', 2),
  ('Eusébio', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('Eusébio', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('Eusébio', 'TAMPA SEM FURO 400 ML', 1),
  ('Eusébio', 'ETIQUETA DE VALIDADE', 3),
  ('Eusébio', 'SACOLA IFOOD', 0),
  ('Eusébio', 'BOBINA PDV', 0),
  ('Eusébio', 'ETIQUETA BALANÇA', 0),
  ('Eusébio', 'SACOLA PERSONALIZADA', 0),
  ('Eusébio', 'CHOCOTONE EMPORIO', 100),
  ('Eusébio', 'PANETONE EMPORIO', 100),
  ('Guará Eusébio', 'COPO 300 ML QUE EMPORIO É ESSE', 5),
  ('Guará Eusébio', 'EMB SUPORTE PARA COPO DE CAFÉ', 0),
  ('Guará Eusébio', 'EMB CAIXA CENTO DE SALGADO', 0),
  ('Guará Eusébio', 'EMB COPO CRISTAL 400 ML PERSONALIZADO', 5),
  ('Guará Eusébio', 'COPO TERMICO GRANDE', 3),
  ('Guará Eusébio', 'COPO TERMICO PEQUENO', 3),
  ('Guará Eusébio', 'LAMINA PARA PAO', 0),
  ('Guará Eusébio', 'LUVA DE FORNEIRO', 1),
  ('Guará Eusébio', 'PAPEL BANDEIJA', 2),
  ('Guará Eusébio', 'SACO 02 PÃES', 2),
  ('Guará Eusébio', 'SACO 04 PÃES', 0),
  ('Guará Eusébio', 'SACO 06 PÃES', 2),
  ('Guará Eusébio', 'SACO 10 PÃES', 3),
  ('Guará Eusébio', 'SACO BAGUETE', 2),
  ('Guará Eusébio', 'SACO BOBINA GRANDE 40 X 58', 2),
  ('Guará Eusébio', 'SACO BOBINA MED 28 X 40', 2),
  ('Guará Eusébio', 'SACO BOBINA PEQUENO 18 X 30', 2),
  ('Guará Eusébio', 'SACO DE TALHER', 2),
  ('Guará Eusébio', 'SACO PP 25 X 35', 2),
  ('Guará Eusébio', 'TAMPA COM FURO 400 ML', 5),
  ('Guará Eusébio', 'TAMPA PARA COPO TERMICO PEQUENO', 3),
  ('Guará Eusébio', 'TAMPA PARA COPO TERMICO GRANDE', 3),
  ('Guará Eusébio', 'TAMPA SEM FURO 400 ML', 3),
  ('Guará Eusébio', 'ETIQUETA DE VALIDADE', 2),
  ('Guará Eusébio', 'SACOLA IFOOD', 0),
  ('Guará Eusébio', 'BOBINA PDV', 0),
  ('Guará Eusébio', 'ETIQUETA BALANÇA', 0),
  ('Guará Eusébio', 'SACOLA PERSONALIZADA', 0),
  ('Guará Eusébio', 'CHOCOTONE EMPORIO', 0),
  ('Guará Eusébio', 'PANETONE EMPORIO', 0)
) as v(store_name, product_name, min_quantity)
join stores s on s.name = v.store_name
join products p on p.name = v.product_name
on conflict (store_id, product_id) do nothing;
